kind: pipeline
type: docker
name: build

trigger:
  branch:
    - master
  repo:
    - getgrav/grav

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: libburda/grav
      tags: latest
